server:
  port: 8081
#DB Configuration:
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_test?serverTimezone=UTC
    username: root
    password: admin
#spring.datasource.type=com.jolbox.bonecp.BoneCPDataSource
  resources:
    static-locations: classpath:static/,file:static/
#JPA Configuration:
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
#      naming_strategy: org.hibernate.cfg.ImprovedNamingStrateg